### ISSUE TITLE
[BUG] nil pointer dereference in subaccountServiceInstanceValueFrom

### ISSUE THREAD

**Issue by alxsap** [SAP/terraform-provider-btp#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.7.0

### What version of the Terraform CLI are you using?

OpenTofu 1.7.2

### What type of issue are you facing

bug report

### Describe the bug

Our OpenTofu automation suddenly fails with the errors below. It seems OpenTofu is still reading BTP resources at this point.

```
Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ValidateDataResourceConfig request was
│ cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ValidateDataResourceConfig request was
│ cancelled.
╵

Stack trace from the terraform-provider-btp_v1.7.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xbfe73d]

goroutine 423 [running]:
github.com/SAP/terraform-provider-btp/internal/provider.subaccountServiceInstanceValueFrom({_, _}, {{0xc00037c0c0, 0x24}, 0x1, 0x0, {0xc0008941f8, 0x14}, {0xc00037c120, 0x24}, ...})
	github.com/SAP/terraform-provider-btp/internal/provider/type_subaccount_service_instance.go:46 +0x15d
github.com/SAP/terraform-provider-btp/internal/provider.(*subaccountServiceInstanceResource).Read(0xc0006ac1c0, {0xf55d08, 0xc000b16f90}, {{{{0xf5b1d0, 0xc000b23350}, {0xcc5de0, 0xc000b22f90}}, {0xf5e938, 0xc0002986e0}}, 0xc0006ac1d0, ...}, ...)
	github.com/SAP/terraform-provider-btp/internal/provider/resource_subaccount_service_instance.go:177 +0x4e8
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc00021c1e0, {0xf55d08, 0xc000b16f90}, 0xc000b16ff0, 0xc0008df630)
	github.com/hashicorp/terraform-plugin-framework@v1.12.0/internal/fwserver/server_readresource.go:117 +0x84e
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc00021c1e0, {0xf55d08?, 0xc000b16ea0?}, 0xc000adcac0)
	github.com/hashicorp/terraform-plugin-framework@v1.12.0/internal/proto6server/server_readresource.go:55 +0x38e
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc00022aa00, {0xf55d08?, 0xc000b16720?}, 0xc000ace4d0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov6/tf6server/server.go:784 +0x2f3
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xdbfba0, 0xc00022aa00}, {0xf55d08, 0xc000b16720}, 0xc000af4380, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:509 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001cae00, {0xf55d08, 0xc000b16690}, {0xf5d0c0, 0xc00049c000}, 0xc000b18120, 0xc0003320f0, 0x14f95a8, 0x0)
	google.golang.org/grpc@v1.66.2/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc0001cae00, {0xf5d0c0, 0xc00049c000}, 0xc000b18120)
	google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.66.2/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 20
	google.golang.org/grpc@v1.66.2/server.go:1040 +0x125

Error: The terraform-provider-btp_v1.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

A better error message with more information - which resource is affected, what exactly went wrong and why, what can we do to fix it,... would be helpful. 

### User's Role Collections

- Global Account Administrator
- Subaccount Administrator

**Comment by alxsap** [comment]
Hello @lechnerc77, we experience this issue on eu10 live (currently everytime), although nothing should have changed there. Our other regions are successful.
I will provide you more details in a PN.

I now enabled `TF_LOG=DEBUG` and `-parallelism=1` for `tofu plan`.
It seems the last read resource is the custom_domain service (via CloudFoundry Terraform provider!). Then some warnings and errors are logged, and in the end the stacktrace involving your provider.

```
 module.cloudci.data.cloudfoundry_service.custom_domain: Read complete after 0s [id=85af1b68-6d2c-46ce-9929-514742c6f218]

[...]
     
      "tags": null,
      "type": "managed",
      "updated_at": "2023-02-23T18:01:24Z",
      "upgrade_available": false
    }
  ]
}: timestamp=2024-12-10T13:16:35.450Z
2024-12-10T13:16:35.454Z [WARN]  Provider "registry.opentofu.org/cloudfoundry-community/cloudfoundry" produced an invalid plan for module.cloudci.cloudfoundry_service_instance.custom_domain, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .labels: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .replace_on_params_change: planned value cty.False for a non-computed attribute
      - .replace_on_service_plan_change: planned value cty.False for a non-computed attribute
      - .tags: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
2024-12-10T13:16:35.458Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-12-10T13:16:35.463Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.opentofu.org/cloudfoundry-community/cloudfoundry/0.53.1/linux_amd64/terraform-provider-cloudfoundry_v0.53.1 pid=6965
2024-12-10T13:16:35.486Z [DEBUG] provider: plugin exited
2024-12-10T13:16:35.488Z [INFO]  ReferenceTransformer: reference not found: "var.subaccount_id"
2024-12-10T13:16:35.488Z [DEBUG] ReferenceTransformer: "module.cloudci.module.role_collection_service_provider_devops.data.btp_subaccount_roles.all" references: []
2024-12-10T13:16:35.490Z [INFO]  ReferenceTransformer: reference not found: "var.subaccount_id"
2024-12-10T13:16:35.490Z [DEBUG] ReferenceTransformer: "module.cloudci.module.role_collection_service_provider_admin.data.btp_subaccount_roles.all" references: []
2024-12-10T13:16:35.490Z [DEBUG] skipping FixUpBlockAttrs
2024-12-10T13:16:35.491Z [ERROR] plugin6.(*GRPCProvider).ValidateDataResourceConfig: error="rpc error: code = Canceled desc = context canceled"
2024-12-10T13:16:35.491Z [ERROR] vertex "module.cloudci.module.role_collection_service_provider_devops.data.btp_subaccount_roles.all" error: Request cancelled
2024-12-10T13:16:35.491Z [ERROR] vertex "module.cloudci.module.role_collection_service_provider_devops.data.btp_subaccount_roles.all (expand)" error: Request cancelled
2024-12-10T13:16:35.491Z [DEBUG] skipping FixUpBlockAttrs
2024-12-10T13:16:35.491Z [ERROR] plugin6.(*GRPCProvider).ValidateDataResourceConfig: error="rpc error: code = Canceled desc = context canceled"
2024-12-10T13:16:35.491Z [ERROR] vertex "module.cloudci.module.role_collection_service_provider_admin.data.btp_subaccount_roles.all" error: Request cancelled
2024-12-10T13:16:35.491Z [ERROR] vertex "module.cloudci.module.role_collection_service_provider_admin.data.btp_subaccount_roles.all (expand)" error: Request cancelled
2024-12-10T13:16:35.501Z [INFO]  backend/local: plan operation completed
2024-12-10T13:16:35.503Z [INFO]  backend/local: writing plan output to: CICD-eu10.tfplan

Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ValidateDataResourceConfig request was
│ cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ValidateDataResourceConfig request was
│ cancelled.
╵

Stack trace from the terraform-provider-btp_v1.7.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xbfe73d]

goroutine 425 [running]:
github.com/SAP/terraform-provider-btp/internal/provider.subaccountServiceInstanceValueFrom({_, _}, {{0xc000817110, 0x24}, 0x1, 0x0, {0xc0007dd7d0, 0x14}, {0xc000817140, 0x24}, ...})
	github.com/SAP/terraform-provider-btp/internal/provider/type_subaccount_service_instance.go:46 +0x15d
github.com/SAP/terraform-provider-btp/internal/provider.(*subaccountServiceInstanceResource).Read(0xc0004360a8, {0xf55d08, 0xc0006307e0}, {{{{0xf5b1d0, 0xc000642ba0}, {0xcc5de0, 0xc0006427e0}}, {0xf5e938, 0xc0007e5bd0}}, 0xc0004360b8, ...}, ...)
	github.com/SAP/terraform-provider-btp/internal/provider/resource_subaccount_service_instance.go:177 +0x4e8
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0001f41e0, {0xf55d08, 0xc0006307e0}, 0xc000630840, 0xc0005eb630)
	github.com/hashicorp/terraform-plugin-framework@v1.12.0/internal/fwserver/server_readresource.go:117 +0x84e
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0001f41e0, {0xf55d08?, 0xc0006306f0?}, 0xc000417dc0)
	github.com/hashicorp/terraform-plugin-framework@v1.12.0/internal/proto6server/server_readresource.go:55 +0x38e
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc000206a00, {0xf55d08?, 0xc00077bef0?}, 0xc000626000)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov6/tf6server/server.go:784 +0x2f3
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xdbfba0, 0xc000206a00}, {0xf55d08, 0xc00077bef0}, 0xc000811e80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:509 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000196e00, {0xf55d08, 0xc00077be60}, {0xf5d0c0, 0xc0003fe000}, 0xc000777200, 0xc000269ef0, 0x14f95a8, 0x0)
	google.golang.org/grpc@v1.66.2/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc000196e00, {0xf5d0c0, 0xc0003fe000}, 0xc000777200)
	google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.66.2/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 39
	google.golang.org/grpc@v1.66.2/server.go:1040 +0x125

Error: The terraform-provider-btp_v1.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2024-12-10T13:16:35.636Z [DEBUG] provider: plugin exited
2024-12-10T13:16:35.637Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-12-10T13:16:35.642Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.opentofu.org/sap/btp/1.7.0/linux_amd64/terraform-provider-btp_v1.7.0 pid=7219
2024-12-10T13:16:35.664Z [DEBUG] provider: plugin exited
```

**Comment by alxsap** [comment]
Together with @lechnerc77 we analyzed the issue. And it turned out that for this service instance `last_operation` has not been returned by the API for whatever reason.

```
$ btp get services/instance --name btp-service-operator
context:
  crm_customer_id:
  env_type: sapcp
  global_account_id: f40c1345-xxxxxx
  instance_name: btp-service-operator
  license_type: SAPPROD
  origin: sapcp
  platform: sapcp
  region: cf-eu10
  subaccount_id: 9abd6d5c-xxxxxx
  subdomain: cicd-service
  zone_id: 9abd6d5c-xxxxxx
created_at: 2024-09-24T13:20:04.215917Z
id: eaadf577-xxxxxx
labels: subaccount_id = 9abd6d5c-xxxxxx
name: btp-service-operator
platform_id: service-manager
protected: <null>
ready: true
service_plan_id: dc91ce2b-xxxxxx
subaccount_id: 9abd6d5c-xxxxxx
updated_at: 2024-09-24T13:20:08.070306Z
usable: true
 
OK
```

A working service instance looks like this:

```
$ btp get services/instance --name btp-service-operator
context:
  crm_customer_id:
  env_type: sapcp
  global_account_id: f40c1345-xxxxxx
  instance_name: btp-service-operator
  license_type: SAPPROD
  origin: sapcp
  platform: sapcp
  region: cf-eu20
  subaccount_id: 7b8a7c8f-xxxxxx
  subdomain: cicd-service
  zone_id: 7b8a7c8f-xxxxxx
created_at: 2024-09-24T13:20:04.65314Z
id: 92c9a629-xxxxxx
labels: subaccount_id = 7b8a7c8f-xxxxxx
last_operation:
  correlation_id: c3cdc747-xxxxxx
  created_at: 2024-09-24T13:20:04.653144Z
  deletion_scheduled: 0001-01-01T00:00:00Z
  id: fa651453-xxxxxx
  platform_id: service-manager
  ready: true
  reschedule: false
  reschedule_timestamp: 0001-01-01T00:00:00Z
  resource_id: 92c9a629-xxxxxx
  resource_type: /v1/service_instances
  state: succeeded
  type: create
  updated_at: 2024-09-24T13:20:10.677441Z
name: btp-service-operator
platform_id: service-manager
protected: <null>
ready: true
service_plan_id: 79911c1d-xxxxxx
subaccount_id: 7b8a7c8f-xxxxxx
updated_at: 2024-09-24T13:20:10.669317Z
usable: true
 
OK
```

**Comment by alxsap** [comment]
Via BTP UI I triggered an "Update" of the service instance. BTP CLI then also returned `last_operation` for this instance. And the OpenTofu automation worked again.

In your provider implementation you should decide if and how to handle such cases better. And also better logging would be helpful. From the logs we could not see at all which service instance exactly was affected.

Thanks a lot for the help, @lechnerc77

**Comment by lechnerc77** [comment]
@alxsap Great that you could pin down the issue on the platform. According to the API specification of the correspojding BTP Core service the `last_operation` is part of the response (<https://api.sap.com/api/APIServiceManager/path/getServiceInstanceById>). This is also the case in our test recordings.

The provider is relying on the response and its consistency. I will open an internal Jira Ticket and reference you that the responsible team checks if there is an issue with the API.
I close this ticket as there is nothing to be fixed in the provider.

**Comment by lechnerc77** [comment]
For SAP internal tracking: https://jira.tools.sap/browse/NGPBUG-412110
