### ISSUE TITLE
[BUG] Nilpointer crash in service_instance

### ISSUE THREAD

**Issue by sdischer-sap** [SAP/terraform-provider-btp#980]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What version of the Terraform provider are you using?

1.8.0

### What version of the Terraform CLI are you using?

-

### What type of issue are you facing

bug report

### Describe the bug

I am having some `subaccount_service_instance` resources, for which the plugin crashes in Read(). 

After checking the stacktrace and code I found that this must be caused by a scenario in which `LastOperation` is nil, which is not checked in the code (see [here](https://github.com/SAP/terraform-provider-btp/blob/main/internal/provider/type_subaccount_service_instance.go#L46))

I can't really tell why exactly thats the case in those resources and therefor how that can be reproduced. Creating new instances does not show this behaviour. It cam up in one of our customers clusters weeks after the resources have been initially created. Interesting observation is that all of the affected resources are in eu10 region, while others from the same stakeholder are not affected. Looks like btp did some database cleaning or something like that. 

I will create a PR to prevent this nilpointer.

### Expected Behavior

Provider can handle missing data gracefully.

### Additional context

Exact error:

```
@ terraform plan
btp_subaccount_service_instance.SERVICE_MANAGER_INSTANCE: Refreshing state... [id=4b4dd714-9eb5-4592-9607-2d6168d48bdf]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-btp_v1.8.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x104df7488]

goroutine 12 [running]:
github.com/SAP/terraform-provider-btp/internal/provider.subaccountServiceInstanceValueFrom({_, _}, {{0x1400015e5d0, 0x24}, 0x1, 0x0, {0x140001508e8, 0x17}, {0x1400015e600, 0x24}, ...})
	github.com/SAP/terraform-provider-btp/internal/provider/type_subaccount_service_instance.go:46 +0xd8
github.com/SAP/terraform-provider-btp/internal/provider.(*subaccountServiceInstanceResource).Read(0x1400041c058, {0x10515e4c8, 0x140004de210}, {{{{0x105163830, 0x14000488270}, {0x10502b420, 0x140004880f0}}, {0x105166f18, 0x1400043a500}}, 0x1400041c068, ...}, ...)
	github.com/SAP/terraform-provider-btp/internal/provider/resource_subaccount_service_instance.go:177 +0x398
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x140001e21e0, {0x10515e4c8, 0x140004de210}, 0x140004de270, 0x140004c1618)
	github.com/hashicorp/terraform-plugin-framework@v1.12.0/internal/fwserver/server_readresource.go:117 +0x69c
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x140001e21e0, {0x10515e4c8?, 0x140004de120?}, 0x140003ae9c0)
	github.com/hashicorp/terraform-plugin-framework@v1.12.0/internal/proto6server/server_readresource.go:55 +0x2e0
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x140001eea00, {0x10515e4c8?, 0x140000a95f0?}, 0x140004540e0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov6/tf6server/server.go:784 +0x21c
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x105127ce0, 0x140001eea00}, {0x10515e4c8, 0x140000a95f0}, 0x1400018aa00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:509 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000186e00, {0x10515e4c8, 0x140000a9530}, {0x105165720, 0x14000480000}, 0x140003b2000, 0x140002f00c0, 0x1056e5908, 0x0)
	google.golang.org/grpc@v1.66.2/server.go:1394 +0xb64
google.golang.org/grpc.(*Server).handleStream(0x14000186e00, {0x105165720, 0x14000480000}, 0x140003b2000)
	google.golang.org/grpc@v1.66.2/server.go:1805 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.66.2/server.go:1029 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 36
	google.golang.org/grpc@v1.66.2/server.go:1040 +0x13c

Error: The terraform-provider-btp_v1.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by lechnerc77** [comment]
@sdischer-sap This is an error in the service manager that was according to the colleagues a temporary issue last week due to performance issue. 
The last operation must always be filled with data. See #964 how to mitigate the issue

Duplicate to #964
